*&---------------------------------------------------------------------*
*& Include          ZLSP012_SHOW04_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK b2. " WITH FRAME TITLE text-b02.

SELECTION-SCREEN COMMENT 5(45) TEXT-b02.
SELECTION-SCREEN ULINE /5(50).

SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS r_single RADIOBUTTON GROUP rb DEFAULT 'X' USER-COMMAND rq1.
SELECTION-SCREEN COMMENT 5(15) TEXT-p01 FOR FIELD r_single.

PARAMETERS r_facmet RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 30(15) TEXT-p03 FOR FIELD r_facmet.

PARAMETERS r_absfac RADIOBUTTON GROUP rb .
SELECTION-SCREEN COMMENT 50(25) TEXT-p02 FOR FIELD r_absfac.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS r_build RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 5(25) TEXT-p04 FOR FIELD r_build.

PARAMETERS r_proto RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 40(25) TEXT-p05 FOR FIELD r_proto.


SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN ULINE /5(50).
SELECTION-SCREEN SKIP.
*SELECTION-SCREEN END OF BLOCK b2.
*
*SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE text-b03.

"SELECTION-SCREEN ULINE.
SELECTION-SCREEN COMMENT /5(50) TEXT-b03.
SELECTION-SCREEN ULINE /5(50).


SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS r_adapt RADIOBUTTON GROUP rb .
SELECTION-SCREEN COMMENT 5(15) TEXT-p06 FOR FIELD r_adapt.

PARAMETERS r_bridg RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 30(15) TEXT-p07 FOR FIELD r_bridg.

PARAMETERS r_compo RADIOBUTTON GROUP rb .
SELECTION-SCREEN COMMENT 50(25) TEXT-p08 FOR FIELD r_compo.

SELECTION-SCREEN END OF LINE.



SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS r_decor RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 15(25) TEXT-p09 FOR FIELD r_decor.

PARAMETERS r_facad RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 50(25) TEXT-p10 FOR FIELD r_facad.

SELECTION-SCREEN END OF LINE.
*
SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS r_flywei RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 15(25) TEXT-p11 FOR FIELD r_flywei.

PARAMETERS r_proxy RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 50(25) TEXT-p12 FOR FIELD r_proxy.

SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN ULINE /5(50).
SELECTION-SCREEN SKIP.


""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""""""""""""""""""""""""""""""""""""""""""""

SELECTION-SCREEN COMMENT /5(50) TEXT-b04.
SELECTION-SCREEN ULINE /5(50).

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS r_chofr RADIOBUTTON GROUP rb .
SELECTION-SCREEN COMMENT 5(25) TEXT-p31 FOR FIELD r_chofr.

PARAMETERS r_itera RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 40(15) TEXT-p32 FOR FIELD r_itera.

SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS r_cmd RADIOBUTTON GROUP rb .
SELECTION-SCREEN COMMENT 5(15) TEXT-p40 FOR FIELD r_cmd.

SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS r_mediat RADIOBUTTON GROUP rb .
SELECTION-SCREEN COMMENT 5(20) TEXT-p33 FOR FIELD r_mediat.

PARAMETERS r_mement RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 30(15) TEXT-p34 FOR FIELD r_mement.

PARAMETERS r_observ RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 50(25) TEXT-p35 FOR FIELD r_observ.

SELECTION-SCREEN END OF LINE.
*




SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS r_state RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 5(20) TEXT-p36 FOR FIELD r_state.

PARAMETERS strat RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 30(15) TEXT-p37 FOR FIELD strat.

SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS r_tmplme RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 5(15) TEXT-p38 FOR FIELD r_tmplme.

PARAMETERS r_visito RADIOBUTTON GROUP rb.
SELECTION-SCREEN COMMENT 30(15) TEXT-p39 FOR FIELD r_visito.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN ULINE /5(50).
SELECTION-SCREEN SKIP.

SELECTION-SCREEN END OF BLOCK b2.
